services:
  webtop:
    image: ghcr.io/linuxserver/webtop:ubuntu-mate
    container_name: webtop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Merida
    volumes:
      - /path/to/data:/config
    ports:
      - 3000:3000
      - 3001:3001
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=web

      # Router
      - traefik.http.routers.webtop.rule=Host(`webtop.pinomagana.local`)
      - traefik.http.routers.webtop.entrypoints=web

      # Service -> puerto HTTPS interno
      - traefik.http.services.webtop.loadbalancer.server.port=3001

      # 👇 backend usa HTTPS
      - traefik.http.services.webtop.loadbalancer.server.scheme=https

      # 👇 ignora self-signed cert del contenedor
      - traefik.http.serverstransports.webtoptransport.insecureskipverify=true
      - traefik.http.services.webtop.loadbalancer.serverstransport=webtoptransport
    shm_size: "3gb"
    restart: unless-stopped

networks:
  web:
    external: true