version: "3.8"

services:
  wud:
    image: getwud/wud
    container_name: wud
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wud.rule=Host(`wud.pinomagana.local`)"
      - "traefik.http.services.wud.loadbalancer.server.port=3000"

networks:
  web:
    external: true