version: "3.8"

services:
  filebrowser:
    image: gtstef/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    user: "1000:1000"

    environment:
      - TZ=America/Merida

    volumes:
      - ./config:/config
      - /mnt/storage:/srv

    networks:
      - web

    labels:
      - traefik.enable=true

      # Red de Traefik
      - traefik.docker.network=web

      # Router
      - traefik.http.routers.filebrowser.rule=Host(`files.pinomagana.local`)
      - traefik.http.routers.filebrowser.entrypoints=web

      # Servicio
      - traefik.http.services.filebrowser.loadbalancer.server.port=8080

networks:
  web:
    external: true